import { Category } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'physical-touch',
    name: 'Physical Touch & Physical Intimacy',
    color: '#F4A89A',
    watercolorClass: 'watercolor-peach',
    subcategories: [
      'Hand Buddies',
      'Massage / Therapeutic Touch',
      'Shared Cuddles',
      'Sleeping Buddies',
      'Dance Buddies',
      'Nudity',
      'Sensual Interactions',
      'Sexual Interactions',
    ],
  },
  {
    id: 'life-structure',
    name: 'Life Structure / Logistics & Agreements',
    color: '#89CFF0',
    watercolorClass: 'watercolor-blue',
    subcategories: [
      'Professional / Work',
      'Co-Parents / Caregivers',
      'Housemates / Domestic Living',
      'Lending Money',
      'Legal & Financial Bonds',
      'Co-owning',
      'Power of Attorney',
      'Marriage / Civil Partnership',
      'Creative Collaborations',
      'Academic Collaborations',
      'Adoption',
      'Shared Finances / Meal Sharing',
      'Legal Processes',
    ],
  },
  {
    id: 'emotional-connection',
    name: 'Emotional Connection',
    color: '#C5A3CF',
    watercolorClass: 'watercolor-lavender',
    subcategories: [
      'Emotional Caregivers',
      'Emotional Support (outside the relationship)',
      'Emotional Process Partners (within the relationship)',
      'Feeds Self Growth',
      'Support Person',
    ],
  },
  {
    id: 'social',
    name: 'Social',
    color: '#F5D06E',
    watercolorClass: 'watercolor-gold',
    subcategories: [
      'Common Interests',
      'Intellectual Connection',
      'Sense of Humor',
      'Shared Play',
      'Spiritual / Religious',
      'Shared Causes / Politics',
      'Shared Community',
      'Shared Learning',
      'Shared Adventure',
    ],
  },
  {
    id: 'time-rhythm',
    name: 'Time & Rhythm',
    color: '#A8C5A0',
    watercolorClass: 'watercolor-sage',
    subcategories: [
      'Daily texting',
      'A few times a week',
      'Weekly check-ins',
      'Monthly catch-ups',
      'Organic / Intermittent',
      'Recurring scheduled calls',
      'Live together',
      'See each other weekly',
      'A few times a month',
      'Occasional visits',
      'From time to time',
      'A few times a year',
      'Seasonal trips',
      'Seasonal living',
    ],
  },
  {
    id: 'frames',
    name: 'Frames',
    color: '#F2B5B5',
    watercolorClass: 'watercolor-rose',
    subcategories: [
      'Friendship',
      'Companionship',
      'Partnership',
      'Collaborator',
      'Romantic Love',
      'Erotic',
      'Attachment Figure',
      'Therapeutic',
    ],
  },
  {
    id: 'qualities',
    name: 'Dynamics',
    color: '#B8A9D4',
    watercolorClass: 'watercolor-purple',
    subcategories: [
      'Kink',
      'Exclusivity',
      'Hierarchy',
      'Teacher & Student',
      'Parent & Child',
      'Facilitator & Participant',
    ],
  },
];
