export const SUBCATEGORY_DEFINITIONS: Record<string, string> = {
  // Physical Touch & Physical Intimacy
  'Hand Buddies': 'Casual, comfortable hand-to-hand contact — holding hands, hand massages, playing with fingers',
  'Massage / Therapeutic Touch': 'Intentional bodywork or healing touch — giving/receiving massages, energy work, therapeutic holding',
  'Shared Cuddles': 'Cuddling together — on the couch, in bed, spooning, resting on each other',
  'Sleeping Buddies': 'Sharing sleep space — napping together, sleeping in the same bed, co-sleeping',
  'Dance Buddies': 'Moving together — partner dance, ecstatic dance, freestyle movement, contact improv',
  'Hand Holding': 'Walking hand-in-hand, interlocking fingers — a simple gesture of closeness and presence',
  'Nudity': 'Being naked together comfortably — hot springs, skinny dipping, changing together, body comfort',
  'Sex and Eros': 'Sexual energy and erotic connection — desire, passion, sexual chemistry',
  'Sensual Interactions': 'Non-sexual but sensory-rich experiences — sharing scents, feeding each other, soft touch, eye gazing',
  'Sexual Interactions': 'Explicit sexual activity — the physical expression of sexual connection',

  // Life Structure / Logistics & Agreements
  'Professional / Work': 'Working together in a professional context — colleagues, business partners, collaborators',
  'Co-Parents / Caregivers': 'Sharing responsibility for raising children or caring for dependents together',
  'Housemates / Domestic Living': 'Living under the same roof — sharing a home, managing household life together',
  'Lending Money': 'Financial trust and support — lending or borrowing money from each other',
  'Legal & Financial Bonds': 'Formal financial entanglement — joint accounts, shared debts, financial agreements',
  'Co-owning': 'Owning property or assets together — a house, car, business, or other shared ownership',
  'Power of Attorney': 'Legal authority to make decisions on each other\'s behalf — medical, financial, or legal',
  'Marriage / Civil Partnership': 'A formal legal union — marriage, civil partnership, domestic partnership',
  'Creative Collaborations': 'Making art, music, writing, or building creative projects together',
  'Academic Collaborations': 'Learning, studying, or researching together in an educational or intellectual context',
  'Adoption': 'Formally adopting children together or being part of an adoption process',
  'Shared Finances / Meal Sharing': 'Pooling resources for daily life — grocery sharing, cooking together, splitting costs',
  'Legal Processes': 'Navigating legal systems together — immigration, custody, contracts, wills',

  // Emotional Connection
  'Emotional Caregivers': 'Being a primary source of emotional care — the person who shows up when things fall apart',
  'Emotional Support (outside the relationship)': 'Supporting each other through challenges with other people — family drama, work stress, other relationships',
  'Emotional Process Partners (within the relationship)': 'Processing feelings about the relationship itself together — navigating tension, growth, and change between you',
  'Feeds Self Growth': 'This connection actively supports personal development — they challenge you, inspire you, help you become more yourself',
  'Support Person': 'A reliable anchor — someone you can count on for practical and emotional backup',

  // Social
  'Common Interests': 'Shared hobbies, passions, or topics you both geek out about',
  'Intellectual Connection': 'Deep thinking together — stimulating conversations, exploring ideas, philosophical exchange',
  'Sense of Humor': 'You make each other laugh — shared humor, inside jokes, playful banter',
  'Shared Play': 'Playing together — games, sports, goofing around, being silly, having fun',
  'Spiritual / Religious': 'Sharing spiritual practices, beliefs, or seeking together — meditation, prayer, ceremony, retreats',
  'Shared Causes / Politics': 'United by shared values and action — activism, political engagement, community organizing',
  'Shared Community': 'Belonging to the same communities — friend groups, neighborhoods, scenes, networks',
  'Shared Learning': 'Growing knowledge together — taking classes, reading the same books, teaching each other',
  'Shared Adventure': 'Exploring the world together — travel, road trips, trying new things, stepping into the unknown',

  // Time & Rhythm
  'Daily texting': 'You message each other most days — a steady stream of connection through words',
  'A few times a week': 'Regular but not daily — enough to stay in each other\'s lives without being constant',
  'Weekly check-ins': 'A weekly rhythm of catching up — intentional or organic, but reliable',
  'Monthly catch-ups': 'You connect about once a month — enough to maintain the thread, with space in between',
  'Organic / Intermittent': 'No set pattern — connection happens naturally when it feels right, with an easy ebb and flow between contact and space',
  'From time to time': 'You see each other occasionally — not on a schedule, but it happens and it matters when it does',
  'Recurring scheduled calls': 'You have a standing call or video date — a chosen ritual of connection',
  'Live together': 'You share a home — daily proximity, woven into each other\'s routines',
  'See each other weekly': 'You spend time together in person most weeks',
  'A few times a month': 'You see each other a couple times a month — regular but not constant',
  'A few times a year': 'Your in-person time is more rare — but often more intentional because of it',
  'Seasonal trips': 'You travel or gather together at certain times of year — a seasonal ritual',
  'Occasional visits': 'You see each other now and then — not regular, but meaningful when it happens',
  'Seasonal living': 'You live together or near each other during specific seasons — a migration pattern of connection',

  // Frames
  'Friendship': 'A bond built on mutual affection, trust, and chosen connection — the foundation of many relationships',
  'Companionship': 'Being each other\'s company — presence, togetherness, doing life side by side',
  'Partnership': 'A sense of being partners in some way — building something together, moving through life as a team',
  'Collaborator': 'Someone you create with — projects, ideas, ventures, art — the relationship is partly defined by what you make together',
  'Romantic Love': 'Heart-centered romantic feelings — butterflies, longing, tenderness, romantic affection',
  'Erotic': 'An erotic charge or energy between you — not necessarily acted on, but felt and alive',
  'Attachment Figure': 'A primary attachment bond — this person is a safe haven and secure base for you',
  'Therapeutic': 'A relationship with a healing quality — you help each other process, grow, and heal',

  // Qualities
  'Kink': 'Shared kink dynamics or BDSM elements — power play, role dynamics, fetish, exploration',
  'Exclusivity': 'Some form of exclusivity exists — sexual, romantic, or other agreed-upon boundaries',
  'Hierarchy': 'An acknowledged difference in priority, power, or structure within the relationship',
  'Teacher & Student': 'One person mentors or teaches the other — a dynamic of learning and guidance',
  'Parent & Child': 'A parent-child dynamic — biological, chosen, or energetic',
  'Facilitator & Participant': 'One person holds space while the other participates — coaching, facilitation, guidance',

  // ---- Menu: Commitment ----
  'Cohabitation': 'Living together — sharing a home, daily routines, and domestic life',
  'Co-parenting': 'Raising children together — shared responsibilities, decisions, and care',
  'Shared pets': 'Co-owning or co-caring for animals — shared responsibility for their wellbeing',
  'Planning for the future': 'Making plans together that extend into the future — goals, dreams, logistics',
  'Long-term involvement': 'An intention or expectation that the relationship will continue over time',
  'Working through challenges': 'Willingness to stay and work through difficulty rather than walk away',
  'Relationship labels': 'Using words like partner, boyfriend, girlfriend, spouse — naming what you are to each other',
  'Prioritization over other partners': 'This relationship takes precedence in scheduling, decisions, or emotional investment',
  'Home ownership': 'Buying or owning property together — a shared investment in physical space',
  'Power of attorney / wills': 'Legal documents giving each other decision-making power — medical, financial, end-of-life',
  'Support through health challenges': 'Being present and involved through illness, injury, or health crises',

  // ---- Menu: Emotional Intimacy ----
  'Expressing happiness and joy': 'Sharing your excitement, delight, and positive feelings openly with each other',
  'Offering support in hard times': 'Showing up emotionally when things are tough — listening, comforting, being present',
  'Sharing vulnerable feelings': 'Opening up about fears, insecurities, and tender emotions',
  'Saying "I love you"': 'Verbally expressing love — whether casually, deeply, or for the first time',
  'Sharing stories about the past': 'Opening up about your history — childhood, past relationships, formative experiences',
  'Sharing hopes for the future': 'Talking about what you want from life, your dreams, and where you\'re headed',
  'Knowing personal likes and dislikes': 'Learning and remembering each other\'s preferences, tastes, and pet peeves',
  'Pet names': 'Using affectionate nicknames — babe, love, sweetie, or your own inventions',
  'Sharing about mental health': 'Being open about your mental health experiences, diagnoses, or struggles',
  'Supporting mental health work': 'Actively supporting each other\'s therapy, medication, or mental health practices',

  // ---- Menu: Physical Intimacy ----
  'Physical affection': 'Casual, warm touch — hugs, pats on the back, a hand on the shoulder',
  'Public displays of affection': 'Being physically affectionate in public — holding hands, kissing, arms around each other',
  'Hand holding': 'Walking hand-in-hand — a simple gesture of closeness and presence',
  'Cuddling': 'Snuggling together — on the couch, in bed, resting on each other',
  'Massage': 'Giving and receiving bodywork — back rubs, foot massages, intentional touch',
  'Sleeping together': 'Sharing a bed — napping together, spending the night, waking up together',
  'Sensual interactions': 'Non-sexual but sensory-rich experiences — feeding each other, soft touch, eye gazing',
  'Sexual interactions': 'Explicit sexual activity — the physical expression of sexual connection',

  // ---- Menu: Communication ----
  'Daily or frequent check-ins': 'Touching base regularly — a text, a call, a quick "how are you" most days',
  'Texting': 'Communicating through messages — casual, frequent, or in-depth text conversations',
  'Phone / video calls': 'Talking live — phone calls, FaceTime, video chats for real-time connection',
  'Discussing work and hobbies': 'Sharing what you\'re working on, what excites you, your daily pursuits',
  'Discussing family, partners, relationships': 'Talking openly about other people in your lives — family dynamics, other partners, friendships',
  'Discussing politics and current events': 'Engaging with the world together — news, politics, social issues, what\'s happening',
  'Expressing disagreements or hurt feelings': 'Being able to say "that hurt" or "I disagree" — honest emotional feedback',
  'Addressing and resolving conflict': 'Working through disagreements together — repair, compromise, understanding',
  'Radical honesty': 'A commitment to deep truthfulness — no white lies, full transparency, even when uncomfortable',

  // ---- Menu: Social Integration ----
  'Meeting metamours (partners\' other partners)': 'Getting to know your partner\'s other partners — building comfort or friendship across connections',
  'Meeting children': 'Being introduced to and spending time with each other\'s kids',
  'Meeting parents / siblings / extended family': 'Getting to know each other\'s family — holidays, gatherings, building those bridges',
  'Meeting friends': 'Being introduced to each other\'s friend circles — socializing together',
  'Spending time as a couple with friends / family': 'Showing up together at social events — being seen and known as a unit',
  'Positive relationships with metamours': 'Actively fostering good relationships with your partner\'s other partners',
  'Serving as +1 for social events': 'Being each other\'s date to weddings, parties, work events',
  'Presenting as a couple in public': 'Being openly together in the world — people know you\'re a pair',
  'Following on social media': 'Being connected online — following, liking, commenting on each other\'s posts',
  'Presenting as a couple on social media': 'Sharing your relationship publicly online — photos together, relationship status',
  'Joint vacations with family / metamours': 'Traveling together with extended networks — family trips, group vacations',

  // ---- Menu: Quality Time ----
  'Regularly scheduled time together': 'Having a consistent rhythm — a standing date, weekly hangout, or regular check-in',
  'Date nights': 'Intentional one-on-one time — going out, dressing up, making it special',
  'Spending the night': 'Sleeping over — staying at each other\'s places, not just visiting',
  'Shared hobbies or activities': 'Doing things you both enjoy together — cooking, gaming, hiking, crafting',
  'Vacations together': 'Traveling together — trips, getaways, exploring new places as a pair',
  'Calendar night / scheduling initiation': 'Proactively planning time together — putting it on the calendar, making it happen',
  'Spontaneous hangouts': 'Unplanned time together — dropping by, last-minute plans, going with the flow',
  'Parallel play (together, doing separate things)': 'Being in the same space but doing your own thing — cozy independence',

  // ---- Menu: Financial ----
  'Shared bank account(s)': 'Having joint finances — a shared account for mutual expenses or savings',
  'Mutual contributions to vacation / activity fund': 'Pooling money for shared experiences — travel fund, date fund, adventure savings',
  'Financial support': 'Helping each other financially — covering expenses, loans, supporting through tough times',
  'Large gifts': 'Giving or receiving significant gifts — expensive presents, generous gestures',
  'Complete financial integration': 'Fully merging finances — all income and expenses shared, no separate accounts',
  'Shared meal costs': 'Splitting or sharing food expenses — groceries, dining out, cooking together',

  // ---- Menu: Autonomy ----
  'Balance of time together and apart': 'Having a healthy mix of togetherness and independence — neither too clingy nor too distant',
  'Support to pursue independent interests': 'Encouraging each other to follow passions and interests outside the relationship',
  'Maintaining independent friendships': 'Keeping your own friends — not merging all social circles, having your own people',
  'Maintaining independent romantic relationships': 'Freedom to have other romantic connections — with openness and respect',
  'Equal distribution of relationship power': 'Shared decision-making — no one person controls or dominates the dynamic',
  'Alone time': 'Space to be by yourself — recharging, reflecting, doing your own thing without guilt',
};
