export const SUBCATEGORY_DEFINITIONS: Record<string, string> = {
  // ---- Life Infrastructure ----
  'Co-Housing': 'Living together in a shared home — sharing daily space, routines, and domestic life',
  'Sharing a Sleeping Space': 'Regularly sleeping in the same room or bed — beyond just spending the night',
  'Shared Chores': 'Dividing up household tasks together — cleaning, cooking, laundry, taking turns',
  'Shared Meals': 'Regularly eating together — cooking for each other, grocery shopping, meal planning as a unit',
  'Home Ownership': 'Buying or owning property together — a shared investment in physical space and future',
  'Co-Parenting': 'Raising children together — shared responsibilities, decisions, and care regardless of romantic status',
  'Shared Pets/Plants': 'Co-owning or co-caring for animals or plants — shared responsibility for living things',
  'Shared External Caretaking': 'Jointly caring for someone outside the relationship — aging parents, relatives, community members',
  'Emergency Contact': 'Being listed as each other\'s emergency contact — the person who gets the call when something happens',
  'Business Collaborations': 'Working together professionally — co-founding, business partnerships, shared professional ventures',
  'Mutual Aid': 'Showing up for each other with practical support — helping with moves, rides, errands, fixing things',

  // ---- Relational Commitment ----
  'Future Plans Together': 'Making plans that extend into the future — goals, dreams, logistics that assume ongoing connection',
  'Long-Term Involvement': 'An intention or expectation that the relationship will continue over time — building something lasting',
  'Focusing on the "Here and Now"': 'Choosing to stay present rather than defining the future — enjoying what exists without locking it down',
  'Prioritization Over Other Partners': 'This relationship takes precedence in scheduling, decisions, or emotional investment',
  'Relationship Labels': 'Using words like partner, boyfriend, girlfriend, spouse — naming what you are to each other',
  'Exclusivity': 'Some form of exclusivity — sexual, romantic, or other agreed-upon boundaries around outside connections',
  'Working Through Challenges': 'Willingness to stay and work through difficulty rather than walk away — repair over rupture',
  'Reliability': 'Showing up consistently — following through on plans, being dependable, doing what you say you\'ll do',
  'Support Through Health Challenges': 'Being present and involved through illness, injury, or health crises — caregiving and showing up',
  'End of Life Care': 'Commitment to being present at the end of life — hospice care, final wishes, being there through the hardest parts',
  'Allyship': 'Actively advocating for each other — standing up against injustice, supporting identity, being a public ally',

  // ---- Quality Time ----
  'Date Nights': 'Intentional one-on-one time — going out, dressing up, making it special and focused on each other',
  'Spending the Night': 'Sleeping over — staying at each other\'s places, waking up together',
  'Shared Hobbies or Activities': 'Doing things you both enjoy together — cooking, gaming, hiking, crafting, making things',
  'Trips Together': 'Traveling together — trips, getaways, exploring new places as a pair or group',
  'Celebrating Events or Holidays': 'Marking milestones and celebrations together — birthdays, anniversaries, holidays, achievements',
  'Parallel Play': 'Being in the same space but doing your own thing — cozy independence, reading side by side',
  'Activities That Are "Yours"': 'Things you only do together — a special restaurant, a shared tradition, your unique thing',
  'Shared Rituals': 'Repeated meaningful practices — morning coffee together, Sunday walks, weekly movie night',
  'Creative Collaboration': 'Making art, music, writing, or building creative projects together — co-creation',
  'Project Collaboration': 'Working on practical projects together — renovations, events, community initiatives, shared goals',

  // ---- Emotional Intimacy ----
  'Terms of Endearment': 'Using affectionate nicknames — babe, love, sweetie, or your own unique inventions for each other',
  'Offering Emotional Support': 'Showing up emotionally when things are tough — listening, comforting, holding space without fixing',
  'Saying "I Love You"': 'Verbally expressing love — whether casually, deeply, or for the first time',
  'Sharing Longings': 'Opening up about deep desires and yearnings — what you truly want from life, love, and connection',
  'Knowing Personal Likes and Dislikes': 'Learning and remembering each other\'s preferences, tastes, and pet peeves — paying attention',
  'Sharing About Mental Health': 'Being open about your mental health experiences, diagnoses, or struggles without shame',
  'Supporting Mental Health Work': 'Actively supporting each other\'s therapy, medication, or mental health practices and growth',
  'Being a Confidante': 'Being someone\'s trusted keeper of secrets — the person they tell things they don\'t tell anyone else',
  'Words of Affirmation': 'Expressing appreciation, encouragement, and admiration through words — verbal acknowledgment',
  'Expressing Disagreements or Hurt Feelings': 'Being able to say "that hurt" or "I disagree" — honest emotional feedback without fear',
  'Addressing and Resolving Conflict': 'Working through disagreements together — repair, compromise, mutual understanding',
  '3rd Party Support': 'Bringing in outside help for the relationship — couples therapy, mediation, trusted advisors',
  'Being Relied Upon for Support': 'Being someone\'s go-to person — they count on you and you show up consistently',
  'Sharing Vulnerable Feelings': 'Opening up about fears, insecurities, and tender emotions — letting yourself be truly seen',
  'Emotional Intimacy with Others': 'Openness to your partner having deep emotional bonds with other people — compersion for closeness',

  // ---- Physical Intimacy ----
  'Physical Affection': 'Casual, warm touch — pats on the back, a hand on the shoulder, gentle everyday contact',
  'Hugs': 'Embracing each other — quick hello hugs, long tight holds, the kind that says "I\'m here"',
  'Kissing': 'Lips meeting — pecks, deep kisses, forehead kisses, all the ways mouths say hello',
  'Hand Holding': 'Walking hand-in-hand, interlocking fingers — a simple gesture of closeness and presence',
  'Body Contact': 'General physical closeness — leaning against each other, feet touching, bodies near',
  'Public Displays of Affection': 'Being physically affectionate in public — holding hands, kissing, arms around each other in the world',
  'Cuddling': 'Snuggling together — on the couch, in bed, spooning, resting on each other',
  'Massage': 'Giving and receiving bodywork — back rubs, foot massages, intentional therapeutic touch',
  'Co-Sleeping': 'Sharing a bed or sleep space regularly — napping together, waking up side by side',
  'Nudity': 'Being naked together comfortably — hot springs, skinny dipping, changing together, body ease',
  'Sensual Interactions': 'Non-sexual but sensory-rich experiences — feeding each other, soft touch, eye gazing, closeness',
  'Sexual Interactions': 'Explicit sexual activity — the physical expression of sexual connection and desire',
  'Kink': 'Shared kink dynamics or BDSM elements — power play, role dynamics, fetish, exploration together',
  'Sexual Interactions with Others': 'Openness to sexual connections outside this relationship — with transparency and agreements',

  // ---- Social Integration ----
  'Down to Meet Friends': 'Willingness to be introduced to each other\'s friend circles — showing up socially',
  'Down to Meet Metamours': 'Openness to meeting your partner\'s other partners — building comfort across connections',
  'Down to Meet Family': 'Willingness to meet parents, siblings, extended family — stepping into each other\'s family worlds',
  'Integrate with Friends': 'Going beyond meeting — becoming part of each other\'s friend groups, building your own bonds',
  'Integrate with Metamours': 'Building genuine relationships with your partner\'s other partners — kitchen table polyamory, shared meals and ease',
  'Integration with Family': 'Becoming part of each other\'s family fabric — holidays, traditions, being known and welcomed',
  'Supporting Friendships': 'Actively encouraging and supporting each other\'s independent friendships — no jealousy, just care',
  'Supporting Metamour Relationships': 'Actively supporting your partner\'s other relationships — scheduling flexibility, emotional generosity',
  'Presenting as a Social Unit in Public': 'Being openly together in the world — people know you\'re connected and see you as a pair or unit',
  'Presenting as a Social Unit on Social Media': 'Sharing your connection publicly online — photos together, tags, relationship visibility',
  'Serving as +1 for Social Events': 'Being each other\'s date to weddings, parties, work events — showing up together officially',
  'Joint Trips with Family/Friends': 'Traveling together with extended networks — family trips, group vacations, friend getaways',

  // ---- Financial/Legal ----
  'Shared Bank Account(s)': 'Having joint finances — a shared account for mutual expenses, savings, or full merging',
  'Financial Support': 'Helping each other financially — covering expenses, support through tough times, having each other\'s backs',
  'Gifts': 'Giving and receiving gifts — thoughtful presents, generous gestures, material expressions of care',
  'Financial Integration': 'Merging finances beyond a shared account — joint budgeting, shared financial planning and goals',
  'Sharing Costs': 'Splitting expenses together — rent, groceries, dining out, subscriptions, daily life costs',
  'Lending Money': 'Financial trust — lending or borrowing money from each other when needed, without weirdness',
  'Legal Processes': 'Navigating legal systems together — power of attorney, adoption, citizenship sponsorship, wills',
  'Marriage/Civil Partnership': 'A formal legal union — marriage, civil partnership, domestic partnership, legal recognition',

  // ---- Communication ----
  'Texting': 'Communicating through messages — casual, frequent, or in-depth text conversations throughout the day',
  'Phone/Video Calls': 'Talking live — phone calls, FaceTime, video chats for real-time voice-to-voice connection',
  'Voice Messages': 'Sending audio messages — the warmth of hearing each other\'s voice without needing to sync schedules',
  'Discussing Work and Hobbies': 'Sharing what you\'re working on, what excites you, your daily pursuits and passions',
  'Discussing Family, Partners, Relationships': 'Talking openly about other people in your lives — family dynamics, other partners, friendships',
  'Transparency About Other Relationships': 'Being open and honest about other romantic or sexual connections — no secrets, clear communication',
  'Discussing Politics and Current Events': 'Engaging with the world together — news, politics, social issues, what\'s happening around you',
  'Playing and Laughing Together': 'Being silly, playful, and lighthearted — inside jokes, banter, goofing around, shared humor',
  'Intellectual/Philosophical Discussions': 'Deep thinking together — stimulating conversations, exploring ideas, debating, wondering aloud',
  'Sharing Stories About the Past': 'Opening up about your history — childhood, past relationships, formative experiences and memories',
  'Radical Honesty': 'A commitment to deep truthfulness — no white lies, full transparency, even when uncomfortable',
  'Relationship "Check-Ins"': 'Intentional conversations about how the relationship is going — needs, feelings, adjustments, gratitude',

  // ---- Time and Rhythms ----
  'Daily or Frequent Communication': 'Touching base most days — a steady stream of connection through messages, calls, or presence',
  'Unplanned Communication': 'Reaching out spontaneously — calling just because, random texts, sharing things in the moment',
  'Long Distance': 'Maintaining connection across physical distance — making it work when you\'re not in the same place',
  'Expectations Around Responding to Messages': 'Having shared understanding about reply times — what\'s expected, what feels comfortable',
  'Integrated into Daily Life': 'Woven into each other\'s everyday — part of the routine, the fabric of daily existence',
  'Planned Hangouts': 'Scheduling time together in advance — putting it on the calendar, making it intentional',
  'Spontaneous Hangouts': 'Unplanned time together — dropping by, last-minute plans, going with the flow',
  'Regularly Scheduled Time Together': 'Having a consistent rhythm — a standing date, weekly hangout, or regular ritual',
  'Seasonal/Contextual Connecting': 'Connection that ebbs and flows with seasons or life context — summer friends, festival buddies, retreat connections',
  'Weekly Hangouts': 'Seeing each other about once a week — a steady reliable rhythm of connection',
  'Monthly Hangouts': 'Connecting about once a month — enough to maintain the thread with space in between',
  'Yearly Hangouts': 'Seeing each other once or a few times a year — rare but meaningful, often deeply intentional',

  // ---- Tones ----
  'Therapeutic': 'A relationship with a healing quality — you help each other process, grow, and heal through connection',
  'Romantic': 'Heart-centered romantic feelings — butterflies, longing, tenderness, romantic affection and gestures',
  'Companionship': 'Being each other\'s company — presence, togetherness, doing life side by side, steady and warm',
  'Friendship': 'A bond built on mutual affection, trust, and chosen connection — the foundation of many relationships',
  'Erotic': 'An erotic charge or energy between you — desire, sexual chemistry, passion that\'s felt and alive',
  'Chosen Family': 'Treating each other as family by choice — deep commitment, unconditional belonging, permanence by intention',
  'Comet/Seasonal': 'A connection that orbits in and out — intense when together, comfortable with long stretches apart',
};
